<a href="https://colab.research.google.com/github/JasonSCFu/NN-CNN-RNN-basics/blob/main/Tensorflow_and_Keras_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensor basics. What is tensor?

In [5]:
# Tensors are similar to numpy ndarrays
import tensorflow as tf

a = tf.zeros((2,2))
b = tf.ones((2,2))

print(a,b)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32) tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [12]:
a.get_shape()

TensorShape([2, 2])

In [13]:
tf.reshape(a,(1,4))

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 0.]], dtype=float32)>

In [14]:
b*5 + 1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[6., 6.],
       [6., 6.]], dtype=float32)>

In [15]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [16]:
print(a[0,0], a[:,0], a[0,:])

tf.Tensor(0.0, shape=(), dtype=float32) tf.Tensor([0. 0.], shape=(2,), dtype=float32) tf.Tensor([0. 0.], shape=(2,), dtype=float32)


#

In [ ]:
# Multiply a row and column matrix,multiply two TensorFlow constant tensors.

import tensorflow as tf

# Create a Constant op that produces a 1x2 matrix.  The op is
# added as a node to the default graph.
#
# The value returned by the constructor represents the output
# of the Constant op.
matrix1 = tf.constant([[3., 3.]])

# Create another Constant that produces a 2x1 matrix.
matrix2 = tf.constant([[2.],[2.]])

# Create a Matmul op that takes 'matrix1' and 'matrix2' as inputs.
# The returned value, 'product', represents the result of the matrix
# multiplication.
product = tf.matmul(matrix1, matrix2)

print(product)
print(float(product))

tf.Tensor([[12.]], shape=(1, 1), dtype=float32)
12.0


In [ ]:
# subtraction
import tensorflow as tf

x = tf.Variable([1.0, 2.0])
a = tf.constant([3.0, 3.0])

# Add an op to subtract 'a' from 'x'.  Run it and print the result
sub = tf.subtract(x, a)
print(sub)
print(sub.numpy())
# ==> [-2. -1.]

tf.Tensor([-2. -1.], shape=(2,), dtype=float32)
[-2. -1.]


In [ ]:
# Change variable's values
x.assign([4.0, 6.0])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([4., 6.], dtype=float32)>

In [ ]:
# Subtraction from new value
sub = tf.subtract(x, a)
print(sub)
print(sub.numpy())

tf.Tensor([1. 3.], shape=(2,), dtype=float32)
[1. 3.]


In [25]:
# Create a session, define a computation graph, feed data in, get result out
# Encapsulates environment to run graph, a graph encapsulates the computation to perform
# Graph is made of placeholder(aka graph input), constant, operations

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [29]:
session = tf.Session()   # Encapsulates environment to run graph
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
k = tf.constant(1.0)
c = tf.add(a, b)
d = tf.subtract(b, k)
e = tf.multiply(c, d)

In [32]:
# run the graph: Select nodes to evaluate, Specify values for placeholders
session.run(e, feed_dict={a:2.0, b:0.5})

-1.25

In [33]:
session.run(c, feed_dict={a:2.0, b:0.5})

2.5

In [34]:
session.run([e,c], feed_dict={a:2.0, b:0.5})

[-1.25, 2.5]

## build a neural network graph

In [43]:
# tf.Variable: Initialization
b1 = tf.Variable(tf.zeros((2,2)), name="bias")
w1 = tf.Variable(tf.random_normal((2,2)), name="w1")

n_input_nodes = 2
n_output_nodes = 1
x = tf.placeholder(tf.float32, (None, 2))
y = tf.placeholder(tf.float32, (None, 1))
W = tf.Variable(tf.random_normal((n_input_nodes,
n_output_nodes)))
b = tf.Variable(tf.zeros(n_output_nodes))
z = tf.matmul(x, W) + b
out = tf.sigmoid(z)


# Add loss function
loss = tf.reduce_mean(
tf.nn.sigmoid_cross_entropy_with_logits(logits=z, labels=y))

# Add SGD optimizer
learning_rate = 0.02
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=output, labels=y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)
sess.run(optimizer, feed_dict={x: inputs, y:labels})


## Simple TensorFlow Classification: Iris
#### The example will use TensorFlow through Keras, rather than direct TensorFlow

In [ ]:
import pandas as pd
import io
import requests
import numpy as np
from sklearn import metrics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/iris.csv", 
    na_values=['NA', '?'])

# Convert to numpy - Classification
x = df[['sepal_l', 'sepal_w', 'petal_l', 'petal_w']].values
dummies = pd.get_dummies(df['species']) # Classification
species = dummies.columns
y = dummies.values


# Build neural network
model = Sequential()
model.add(Dense(50, input_dim=x.shape[1], activation='relu')) # Hidden 1
model.add(Dense(25, activation='relu')) # Hidden 2
model.add(Dense(y.shape[1],activation='softmax')) # Output

model.compile(loss='categorical_crossentropy', optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

Epoch 1/100
5/5 - 1s - loss: 1.4646 - 672ms/epoch - 134ms/step
Epoch 2/100
5/5 - 0s - loss: 1.2748 - 17ms/epoch - 3ms/step
Epoch 3/100
5/5 - 0s - loss: 1.1494 - 16ms/epoch - 3ms/step
Epoch 4/100
5/5 - 0s - loss: 1.0716 - 15ms/epoch - 3ms/step
Epoch 5/100
5/5 - 0s - loss: 1.0163 - 13ms/epoch - 3ms/step
Epoch 6/100
5/5 - 0s - loss: 0.9697 - 14ms/epoch - 3ms/step
Epoch 7/100
5/5 - 0s - loss: 0.9269 - 14ms/epoch - 3ms/step
Epoch 8/100
5/5 - 0s - loss: 0.8830 - 15ms/epoch - 3ms/step
Epoch 9/100
5/5 - 0s - loss: 0.8390 - 26ms/epoch - 5ms/step
Epoch 10/100
5/5 - 0s - loss: 0.7943 - 13ms/epoch - 3ms/step
Epoch 11/100
5/5 - 0s - loss: 0.7525 - 14ms/epoch - 3ms/step
Epoch 12/100
5/5 - 0s - loss: 0.7151 - 14ms/epoch - 3ms/step
Epoch 13/100
5/5 - 0s - loss: 0.6813 - 21ms/epoch - 4ms/step
Epoch 14/100
5/5 - 0s - loss: 0.6489 - 15ms/epoch - 3ms/step
Epoch 15/100
5/5 - 0s - loss: 0.6135 - 14ms/epoch - 3ms/step
Epoch 16/100
5/5 - 0s - loss: 0.5852 - 19ms/epoch - 4ms/step
Epoch 17/100
5/5 - 0s - loss: 

In [ ]:
print(species)

Index(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='object')


In [ ]:
pred = model.predict(x)
print(f"Shape: {pred.shape}")
print(pred[0:10])

Shape: (150, 3)
[[9.9817193e-01 1.8280980e-03 7.8141742e-09]
 [9.9506170e-01 4.9382546e-03 5.7986675e-08]
 [9.9694592e-01 3.0540687e-03 3.2799946e-08]
 [9.9347323e-01 6.5266807e-03 1.2464123e-07]
 [9.9834621e-01 1.6537571e-03 7.2986519e-09]
 [9.9717003e-01 2.8300178e-03 9.9238076e-09]
 [9.9614859e-01 3.8514065e-03 5.2441017e-08]
 [9.9708742e-01 2.9126452e-03 1.9082528e-08]
 [9.9215502e-01 7.8447377e-03 2.3504626e-07]
 [9.9586052e-01 4.1395593e-03 3.9370065e-08]]


In [ ]:
np.set_printoptions(suppress=True)

In [ ]:
print(y[0:10])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [ ]:
predict_classes = np.argmax(pred,axis=1)
expected_classes = np.argmax(y,axis=1)
print(f"Predictions: {predict_classes}")
print(f"Expected: {expected_classes}")

Predictions: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Expected: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
print(species[predict_classes[1:10]])

Index(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'],
      dtype='object')


In [ ]:
from sklearn.metrics import accuracy_score

correct = accuracy_score(expected_classes,predict_classes)
print(f"Accuracy: {correct}")

Accuracy: 0.98


In [ ]:
sample_flower = np.array( [[5.0,3.0,4.0,2.0]], dtype=float)
pred = model.predict(sample_flower)
print(pred)
pred = np.argmax(pred)
print(f"Predict that {sample_flower} is: {species[pred]}")

[[0.00061115 0.2014582  0.79793066]]
Predict that [[5. 3. 4. 2.]] is: Iris-virginica


In [ ]:
sample_flower = np.array( [[5.0,3.0,4.0,2.0],[5.2,3.5,1.5,0.8]],\
        dtype=float)
pred = model.predict(sample_flower)
print(pred)
pred = np.argmax(pred,axis=1)
print(f"Predict that these two flowers {sample_flower} ")
print(f"are: {species[pred]}")

[[0.00061115 0.2014581  0.7979308 ]
 [0.9903662  0.00963367 0.00000013]]
Predict that these two flowers [[5.  3.  4.  2. ]
 [5.2 3.5 1.5 0.8]] 
are: Index(['Iris-virginica', 'Iris-setosa'], dtype='object')


#Simple TensorFlow Regression: MPG

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import pandas as pd
import io
import os
import requests
import numpy as np
from sklearn import metrics

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", 
    na_values=['NA', '?'])

cars = df['name']

# Handle missing value
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

# Pandas to Numpy
x = df[['cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin']].values
y = df['mpg'].values # regression

# Build the neural network
model = Sequential()
model.add(Dense(25, input_dim=x.shape[1], activation='relu')) # Hidden 1
model.add(Dense(10, activation='relu')) # Hidden 2
model.add(Dense(1)) # Output
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

Epoch 1/100
13/13 - 1s - loss: 1213385.5000 - 920ms/epoch - 71ms/step
Epoch 2/100
13/13 - 0s - loss: 598610.4375 - 40ms/epoch - 3ms/step
Epoch 3/100
13/13 - 0s - loss: 247398.2344 - 38ms/epoch - 3ms/step
Epoch 4/100
13/13 - 0s - loss: 100504.0938 - 37ms/epoch - 3ms/step
Epoch 5/100
13/13 - 0s - loss: 35507.2969 - 44ms/epoch - 3ms/step
Epoch 6/100
13/13 - 0s - loss: 9610.8008 - 38ms/epoch - 3ms/step
Epoch 7/100
13/13 - 0s - loss: 1480.1786 - 31ms/epoch - 2ms/step
Epoch 8/100
13/13 - 0s - loss: 319.5854 - 38ms/epoch - 3ms/step
Epoch 9/100
13/13 - 0s - loss: 105.6841 - 53ms/epoch - 4ms/step
Epoch 10/100
13/13 - 0s - loss: 60.2964 - 34ms/epoch - 3ms/step
Epoch 11/100
13/13 - 0s - loss: 45.1970 - 45ms/epoch - 3ms/step
Epoch 12/100
13/13 - 0s - loss: 40.0576 - 39ms/epoch - 3ms/step
Epoch 13/100
13/13 - 0s - loss: 38.5619 - 38ms/epoch - 3ms/step
Epoch 14/100
13/13 - 0s - loss: 38.0134 - 51ms/epoch - 4ms/step
Epoch 15/100
13/13 - 0s - loss: 37.0669 - 47ms/epoch - 4ms/step
Epoch 16/100
13/13 - 

In [ ]:
pred = model.predict(x)
print(f"Shape: {pred.shape}")
print(pred[0:10])

Shape: (398, 1)
[[14.049168]
 [17.270603]
 [17.872107]
 [17.7543  ]
 [16.108747]
 [15.058154]
 [18.340857]
 [17.981812]
 [18.209995]
 [19.42039 ]]


In [ ]:
# Measure RMSE error.  RMSE is common for regression.
score = np.sqrt(metrics.mean_squared_error(pred,y))
print(f"Final score (RMSE): {score}")

Final score (RMSE): 3.9701933323825274


In [ ]:
# Sample predictions
for i in range(10):
    print(f"{i+1}. Car name: {cars[i]}, MPG: {y[i]}, " f"predicted MPG: {pred[i]}")

1. Car name: chevrolet chevelle malibu, MPG: 18.0, predicted MPG: [14.049168]
2. Car name: buick skylark 320, MPG: 15.0, predicted MPG: [17.270603]
3. Car name: plymouth satellite, MPG: 18.0, predicted MPG: [17.872107]
4. Car name: amc rebel sst, MPG: 16.0, predicted MPG: [17.7543]
5. Car name: ford torino, MPG: 17.0, predicted MPG: [16.108747]
6. Car name: ford galaxie 500, MPG: 15.0, predicted MPG: [15.058154]
7. Car name: chevrolet impala, MPG: 14.0, predicted MPG: [18.340857]
8. Car name: plymouth fury iii, MPG: 14.0, predicted MPG: [17.981812]
9. Car name: pontiac catalina, MPG: 14.0, predicted MPG: [18.209995]
10. Car name: amc ambassador dpl, MPG: 15.0, predicted MPG: [19.42039]


#Saving and Loading a Keras Neural Network
##format:YMAL,JSON,HDF5

In [ ]:
save_path = "."

In [ ]:
# Save neural network structure to JSON (no weights)
model_json = model.to_json()
with open(os.path.join(save_path,"network.json"), "w") as json_file:
    json_file.write(model_json)



In [ ]:
# Stores the complete neural network (with weights)
model.save(os.path.join(save_path,"network.h5"))

In [ ]:
from tensorflow.keras.models import load_model
model2 = load_model(os.path.join(save_path,"network.h5"))